-- TwitchEmotes_SanityCapped
--
-- A companion pack for the TwitchEmotes addon. It does not modify TwitchEmotes;
-- it loads after it and merges its own emotes into the same tables, so custom
-- emotes behave identically to the built-in ones (chat, autocomplete, dropdown,
-- statistics, click-to-insert).
--
-- Emotes themselves live in EmoteData.lua, which is generated by
-- tools/build_emotes.py. Don't edit that file by hand.

local ADDON, ns = ...

local CATEGORY = "Sanity Capped"

local function warn(msg)
	DEFAULT_CHAT_FRAME:AddMessage("|cffff6666" .. ADDON .. ":|r " .. msg)
end

local function info(msg)
	DEFAULT_CHAT_FRAME:AddMessage("|cff8fd4ff" .. CATEGORY .. ":|r " .. msg)
end

-- ---------------------------------------------------------------------------
-- Merging our emotes into TwitchEmotes
-- ---------------------------------------------------------------------------

local loadedCount = 0

local function MergeEmotes()
	-- [emote key] = "Interface\AddOns\...\Foo.tga:28:28"
	for key, path in pairs(ns.pack) do
		TwitchEmotes_defaultpack[key] = path
	end

	-- [typed word] = emote key
	for word, key in pairs(ns.emoticons) do
		TwitchEmotes_emoticons[word] = key
	end

	-- sprite-sheet playback data, keyed by the bare .tga path
	for path, data in pairs(ns.animations) do
		TwitchEmotes_animation_metadata[path] = data
	end

	for _ in pairs(ns.pack) do
		loadedCount = loadedCount + 1
	end
end

-- TwitchEmotes builds its autocomplete list once, during its own ADDON_LOADED,
-- which fires before ours. The list is held by reference inside the editbox
-- library, so appending to it in place is enough to make our emotes suggestable.
local function ExtendAutoComplete()
	if type(AllTwitchEmoteNames) ~= "table" then
		return
	end

	local present = {}
	for _, name in ipairs(AllTwitchEmoteNames) do
		present[name] = true
	end

	for key in pairs(ns.pack) do
		if not present[key] then
			AllTwitchEmoteNames[#AllTwitchEmoteNames + 1] = key
		end
	end

	table.sort(AllTwitchEmoteNames)
end

-- Add our emotes to the chat-bubble dropdown. We do this by hand rather than
-- via TwitchEmotes:AddCategory so that unchecking the category in the options
-- panel actually sticks across sessions (AddCategory re-checks it every load).
local PER_PAGE = 45

local function AddDropdownCategories()
	if type(TwitchEmotes_dropdown_options) ~= "table"
		or type(Emoticons_Settings) ~= "table"
		or type(Emoticons_Settings["FAVEMOTES"]) ~= "table" then
		return
	end

	local page, entry = nil, 0
	local pageNum = 0

	local function newPage()
		pageNum = pageNum + 1
		local label = CATEGORY
		if pageNum > 1 then
			label = CATEGORY .. " " .. pageNum
		end
		page = { label }
		entry = 0

		local index = #TwitchEmotes_dropdown_options + 1
		TwitchEmotes_dropdown_options[index] = page
		if Emoticons_Settings["FAVEMOTES"][index] == nil then
			Emoticons_Settings["FAVEMOTES"][index] = true
		end
	end

	newPage()
	for _, key in ipairs(ns.ordered) do
		if entry >= PER_PAGE then
			newPage()
		end
		page[#page + 1] = key
		entry = entry + 1
	end
end

-- ---------------------------------------------------------------------------
-- Animation support
-- ---------------------------------------------------------------------------
--
-- TwitchEmotesAnimator_UpdateEmoteInFontString advances animated emotes by
-- rewriting the texture escape sequences in a fontstring every tick. Its
-- pattern is hardcoded to "Interface\AddOns\TwitchEmotes\Emotes", so emotes
-- served from our folder would sit frozen on frame 0.
--
-- We wrap the global: the original still handles base-pack emotes, then we run
-- the same pass over our own path root. Wrapping rather than replacing means we
-- keep working if the base addon changes its animation logic.

local function escapePattern(s)
	return (s:gsub("[%^%$%(%)%%%.%[%]%*%+%-%?]", "%%%0"))
end

local function InstallAnimatorHook()
	local original = TwitchEmotesAnimator_UpdateEmoteInFontString
	if type(original) ~= "function" then
		warn("could not hook the animator; custom animated emotes will not play.")
		return
	end

	local root = escapePattern(ns.EMOTE_ROOT)
	local findAll = "(|T" .. root .. ".-|t)"
	local findPath = "|T(" .. root .. ".-%.tga).-|t"

	-- Only + and - need escaping here: the rest of a texture escape sequence is
	-- literal, and this mirrors what the base animator does.
	local function escSubject(s)
		return (s:gsub("%+", "%%+"):gsub("%-", "%%-"))
	end

	local issecret = issecretvalue or function() return false end

	TwitchEmotesAnimator_UpdateEmoteInFontString = function(fontstring, w, h)
		original(fontstring, w, h)

		local txt = fontstring:GetText()
		if txt == nil or issecret(txt) == true then
			return
		end

		for escapeSeq in txt:gmatch(findAll) do
			local path = escapeSeq:match(findPath)
			local anim = path and TwitchEmotes_animation_metadata[path]
			if anim then
				local frame = TwitchEmotes_GetCurrentFrameNum(anim)
				local replacement
				if w ~= nil or h ~= nil then
					replacement = TwitchEmotes_BuildEmoteFrameStringWithDimensions(
						path, anim, frame, w, h)
				else
					replacement = TwitchEmotes_BuildEmoteFrameString(path, anim, frame)
				end

				local newTxt = txt:gsub(escSubject(escapeSeq), replacement)
				-- Chat lines carry their text twice; keep messageInfo in sync or
				-- the line reverts on the next chat repaint.
				if fontstring.messageInfo ~= nil then
					fontstring.messageInfo.message = newTxt
				end
				fontstring:SetText(newTxt)
				txt = newTxt
			end
		end
	end
end

-- ---------------------------------------------------------------------------
-- Slash command
-- ---------------------------------------------------------------------------

local function ShowList()
	local keys = {}
	for key in pairs(ns.pack) do
		keys[#keys + 1] = key
	end
	table.sort(keys)

	info(#keys .. " emote(s):")
	local line, perLine = "", 0
	for _, key in ipairs(keys) do
		line = line .. "|T" .. ns.pack[key] .. "|t " .. key .. "   "
		perLine = perLine + 1
		if perLine == 4 then
			DEFAULT_CHAT_FRAME:AddMessage(line)
			line, perLine = "", 0
		end
	end
	if perLine > 0 then
		DEFAULT_CHAT_FRAME:AddMessage(line)
	end
end

SLASH_SANITYEMOTES1 = "/tesc"
SLASH_SANITYEMOTES2 = "/sanityemotes"
SlashCmdList["SANITYEMOTES"] = function(msg)
	msg = (msg or ""):lower():match("^%s*(.-)%s*$")
	if msg == "list" then
		ShowList()
	else
		info(loadedCount .. " emote(s) loaded. |cffaaaaaa/tesc list|r to see them all.")
	end
end

-- ---------------------------------------------------------------------------
-- Boot
-- ---------------------------------------------------------------------------

local f = CreateFrame("Frame")
f:RegisterEvent("PLAYER_LOGIN")
f:SetScript("OnEvent", function(self)
	self:UnregisterAllEvents()

	if type(TwitchEmotes_defaultpack) ~= "table"
		or type(TwitchEmotes_emoticons) ~= "table"
		or type(TwitchEmotes_animation_metadata) ~= "table" then
		warn("the TwitchEmotes addon is missing or disabled, so no custom "
			.. "emotes were loaded.")
		return
	end

	if type(ns.pack) ~= "table" then
		warn("EmoteData.lua is missing. Run tools/build_emotes.py.")
		return
	end

	MergeEmotes()
	ExtendAutoComplete()
	AddDropdownCategories()
	InstallAnimatorHook()
end)
