-- GENERATED BY tools/build_emotes.py -- DO NOT EDIT BY HAND.
-- Add or remove images in tools/source/ and re-run the script.

local ADDON, ns = ...

-- Resolved from the folder name at load time, so renaming the addon
-- folder (and its .toc to match) does not need a rebuild.
ns.EMOTE_ROOT = "Interface\\AddOns\\" .. ADDON .. "\\Emotes\\"

ns.pack = {
	["scBasedPi"] = ns.EMOTE_ROOT .. "scBasedPi.tga:28:28",
	["scCloudzUlt"] = ns.EMOTE_ROOT .. "scCloudzUlt.tga:28:28",
	["scDinoDance"] = ns.EMOTE_ROOT .. "scDinoDance.tga:28:28",
	["scFuck"] = ns.EMOTE_ROOT .. "scFuck.tga:28:28",
	["scGoldenABEar"] = ns.EMOTE_ROOT .. "scGoldenABEar.tga:28:28",
	["scImIn"] = ns.EMOTE_ROOT .. "scImIn.tga:28:28",
	["scMlgPi"] = ns.EMOTE_ROOT .. "scMlgPi.tga:28:28",
	["scOooo"] = ns.EMOTE_ROOT .. "scOooo.tga:28:28",
	["scPewW"] = ns.EMOTE_ROOT .. "scPewW.tga:28:28",
	["scPiAddiction"] = ns.EMOTE_ROOT .. "scPiAddiction.tga:28:28",
	["scRdjHuh"] = ns.EMOTE_ROOT .. "scRdjHuh.tga:28:28",
	["scSpuggiesUlt"] = ns.EMOTE_ROOT .. "scSpuggiesUlt.tga:28:28",
	["scTheChosen"] = ns.EMOTE_ROOT .. "scTheChosen.tga:28:28",
	["scTheLastTrue"] = ns.EMOTE_ROOT .. "scTheLastTrue.tga:28:28",
	["scTrue"] = ns.EMOTE_ROOT .. "scTrue.tga:28:28",
	["scTurtleKillOrder"] = ns.EMOTE_ROOT .. "scTurtleKillOrder.tga:28:28",
	["scVeryBased"] = ns.EMOTE_ROOT .. "scVeryBased.tga:28:28",
	["scVynChatting"] = ns.EMOTE_ROOT .. "scVynChatting.tga:28:28",
	["scWeAreGathered"] = ns.EMOTE_ROOT .. "scWeAreGathered.tga:28:28",
	["scWhat"] = ns.EMOTE_ROOT .. "scWhat.tga:28:28",
}

ns.emoticons = {
	["scBasedPi"] = "scBasedPi",
	["scCloudzUlt"] = "scCloudzUlt",
	["scDinoDance"] = "scDinoDance",
	["scFuck"] = "scFuck",
	["scGoldenABEar"] = "scGoldenABEar",
	["scImIn"] = "scImIn",
	["scMlgPi"] = "scMlgPi",
	["scOooo"] = "scOooo",
	["scPewW"] = "scPewW",
	["scPiAddiction"] = "scPiAddiction",
	["scRdjHuh"] = "scRdjHuh",
	["scSpuggiesUlt"] = "scSpuggiesUlt",
	["scTheChosen"] = "scTheChosen",
	["scTheLastTrue"] = "scTheLastTrue",
	["scTrue"] = "scTrue",
	["scTurtleKillOrder"] = "scTurtleKillOrder",
	["scVeryBased"] = "scVeryBased",
	["scVynChatting"] = "scVynChatting",
	["scWeAreGathered"] = "scWeAreGathered",
	["scWhat"] = "scWhat",
}

ns.animations = {
	[ns.EMOTE_ROOT .. "scDinoDance.tga"] = {["nFrames"] = 64, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 14},
	[ns.EMOTE_ROOT .. "scImIn.tga"] = {["nFrames"] = 48, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30},
	[ns.EMOTE_ROOT .. "scOooo.tga"] = {["nFrames"] = 64, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18},
	[ns.EMOTE_ROOT .. "scRdjHuh.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 10},
	[ns.EMOTE_ROOT .. "scTheLastTrue.tga"] = {["nFrames"] = 64, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 12},
	[ns.EMOTE_ROOT .. "scVeryBased.tga"] = {["nFrames"] = 64, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 15},
	[ns.EMOTE_ROOT .. "scWeAreGathered.tga"] = {["nFrames"] = 42, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 10},
}

ns.ordered = {
	"scBasedPi",
	"scCloudzUlt",
	"scDinoDance",
	"scFuck",
	"scGoldenABEar",
	"scImIn",
	"scMlgPi",
	"scOooo",
	"scPewW",
	"scPiAddiction",
	"scRdjHuh",
	"scSpuggiesUlt",
	"scTheChosen",
	"scTheLastTrue",
	"scTrue",
	"scTurtleKillOrder",
	"scVeryBased",
	"scVynChatting",
	"scWeAreGathered",
	"scWhat",
}
