#!/usr/bin/env python3
"""Seed the site with the emotes that already shipped in the pack.

Writes seed.sql (D1 rows) and seed_r2.sh (R2 uploads) next to this file, so the
browse page isn't empty and duplicate checks cover the existing emotes.

    py -3.13 web/scripts/seed.py
    npx wrangler d1 execute sanity-capped-emotes --remote --file=web/scripts/seed.sql
    bash web/scripts/seed_r2.sh
"""

import hashlib
import time
import uuid
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SOURCE = ROOT / "tools" / "source"
BUCKET = "sanity-capped-emotes"
UPLOADER = "the vault"

CONTENT_TYPE = {".gif": "image/gif", ".png": "image/png",
                ".webp": "image/webp", ".jpg": "image/jpeg", ".jpeg": "image/jpeg"}


def dhash(path):
    """Same 64-bit difference hash the browser computes in web/public/app.js."""
    with Image.open(path) as im:
        im.seek(0)
        im = im.convert("RGBA").resize((9, 8), Image.BILINEAR)
        px = im.load()
        bits = ""
        for y in range(8):
            row = [(0.299 * px[x, y][0] + 0.587 * px[x, y][1] + 0.114 * px[x, y][2])
                   * (px[x, y][3] / 255) for x in range(9)]
            bits += "".join("1" if row[x] > row[x + 1] else "0" for x in range(8))
    return f"{int(bits, 2):016x}"


def main():
    files = sorted(p for p in SOURCE.iterdir()
                   if p.is_file() and p.suffix.lower() in CONTENT_TYPE)
    now = int(time.time())
    sql = ["-- Generated by web/scripts/seed.py"]
    sh = ["#!/usr/bin/env bash", "set -e",
          "# Pass --local to target the local dev bucket instead of the real one.",
          'REMOTE="${1:---remote}"']

    for f in files:
        data = f.read_bytes()
        sha = hashlib.sha256(data).hexdigest()
        ext = f.suffix.lower().lstrip(".")
        ext = "jpg" if ext == "jpeg" else ext
        eid = str(uuid.uuid4())
        animated = 1 if getattr(Image.open(f), "n_frames", 1) > 1 else 0
        sql.append(
            "INSERT OR IGNORE INTO emotes "
            "(id, name, ext, sha256, dhash, uploader, status, animated, bytes, created_at, decided_at) "
            f"VALUES ('{eid}', '{f.stem}', '{ext}', '{sha}', '{dhash(f)}', '{UPLOADER}', "
            f"'approved', {animated}, {len(data)}, {now}, {now});"
        )
        sh.append(
            f'npx wrangler r2 object put {BUCKET}/emotes/{eid}.{ext} '
            f'--file "{f.relative_to(ROOT).as_posix()}" '
            f'--content-type "{CONTENT_TYPE[f.suffix.lower()]}" $REMOTE'
        )
        print(f"  {f.stem:<22} {len(data)//1024:>4} KB  {'animated' if animated else 'static'}")

    (HERE / "seed.sql").write_text("\n".join(sql) + "\n", encoding="utf-8")
    (HERE / "seed_r2.sh").write_text("\n".join(sh) + "\n", encoding="utf-8")
    print(f"\n{len(files)} emote(s) -> seed.sql + seed_r2.sh")
    print("Approved rows have no github_sha, so removing one from the site needs a manual")
    print("delete in tools/source/ — they're already committed.")


if __name__ == "__main__":
    raise SystemExit(main())
